// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraningsbokningssystemAPI.Data;

#nullable disable

namespace TraningsbokningssystemAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TraningsbokningssystemAPI.Models.Bokning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KundId")
                        .HasColumnType("int");

                    b.Property<int>("TräningsPassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KundId");

                    b.HasIndex("TräningsPassId");

                    b.ToTable("Bokningar");
                });

            modelBuilder.Entity("TraningsbokningssystemAPI.Models.Kund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("TraningsbokningssystemAPI.Models.TräningsPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("datetime2");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Träningspass");
                });

            modelBuilder.Entity("TraningsbokningssystemAPI.Models.Bokning", b =>
                {
                    b.HasOne("TraningsbokningssystemAPI.Models.Kund", "Kund")
                        .WithMany("Bokningar")
                        .HasForeignKey("KundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraningsbokningssystemAPI.Models.TräningsPass", "Pass")
                        .WithMany("Bokningar")
                        .HasForeignKey("TräningsPassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kund");

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("TraningsbokningssystemAPI.Models.Kund", b =>
                {
                    b.Navigation("Bokningar");
                });

            modelBuilder.Entity("TraningsbokningssystemAPI.Models.TräningsPass", b =>
                {
                    b.Navigation("Bokningar");
                });
#pragma warning restore 612, 618
        }
    }
}
